server:
  port: 3030
  
my:
  greeting: Hello Philip application-default
  application:
    name: application-defaul
    profile: default

db:
  server: application-defaul
  host: 171.0.0.1
  user: user1
  psw: psw