my:
  greeting: Hello Philip uuu
  application:
    name: config-server

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo        
