server:
  port: 3032
  
my:
  greeting: Hello Philip application-uat
  application:
    name: application-uat
    profile: application-uat

db:
  server: application-uat
  host: 171.0.0.1
  user: user1
  psw: psw

