server:
  port: 3031
  
my:
  greeting: Hello Philip application-dev
  application:
    name: application-dev
    profile: application-dev

db:
  server: application-dev
  host: 171.0.0.1
  user: user1
  psw: psw

