my:
  greeting: Hello Philip uuu
  application:
    name: config-server

db:
  server: test
  host: 171.0.0.1
  user: user1
  psw:psw

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo        
